namespace StarlightGUI
{
	[bindable]
	[default_interface]
	runtimeclass LogEntryInfo
	{
		LogEntryInfo();

		String Timestamp{ get; set; };
		String Level{ get; set; };
		String Source{ get; set; };
		String Message{ get; set; };
		Int32 LevelInt{ get; set; };
	}
}
