@echo off
cd Release\StarlightGUI
rd af-ZA /s /q
rd am-ET /s /q
rd ar-SA /s /q
rd as-IN /s /q
rd az-Latn-AZ /s /q
rd bg-BG /s /q
rd bn-IN /s /q
rd bs-Latn-BA /s /q
rd ca-ES /s /q
rd ca-Es-VALENCIA /s /q
rd cs-CZ /s /q
rd cy-GB /s /q
rd da-DK /s /q
rd de-DE /s /q
rd el-GR /s /q
rd en-GB /s /q
rd es-ES /s /q
rd es-MX /s /q
rd et-EE /s /q
rd eu-ES /s /q
rd fa-IR /s /q
rd fi-FI /s /q
rd fil-PH /s /q
rd fr-CA /s /q
rd fr-FR /s /q
rd ga-IE /s /q
rd gd-gb /s /q
rd gl-ES /s /q
rd gu-IN /s /q
rd he-IL /s /q
rd hi-IN /s /q
rd hr-HR /s /q
rd hu-HU /s /q
rd hy-AM /s /q
rd id-ID /s /q
rd is-IS /s /q
rd it-IT /s /q
rd ja-JP /s /q
rd ka-GE /s /q
rd kk-KZ /s /q
rd km-KH /s /q
rd kn-IN /s /q
rd kok-IN /s /q
rd ko-KR /s /q
rd lb-LU /s /q
rd lo-LA /s /q
rd lt-LT /s /q
rd lv-LV /s /q
rd mi-NZ /s /q
rd mk-MK /s /q
rd ml-IN /s /q
rd mr-IN /s /q
rd ms-MY /s /q
rd mt-MT /s /q
rd nb-NO /s /q
rd ne-NP /s /q
rd nl-NL /s /q
rd nn-NO /s /q
rd or-IN /s /q
rd pa-IN /s /q
rd pl-PL /s /q
rd pt-BR /s /q
rd pt-PT /s /q
rd quz-PE /s /q
rd ro-RO /s /q
rd ru-RU /s /q
rd sk-SK /s /q
rd sl-SI /s /q
rd sq-AL /s /q
rd sr-Cyrl-BA /s /q
rd sr-Cyrl-RS /s /q
rd sr-Latn-RS /s /q
rd sv-SE /s /q
rd ta-IN /s /q
rd te-IN /s /q
rd th-TH /s /q
rd tr-TR /s /q
rd tt-RU /s /q
rd ug-CN /s /q
rd uk-UA /s /q
rd ur-PK /s /q
rd uz-Latn-UZ /s /q
rd vi-VN /s /q
rd af-ZA /s /q
del RestartAgent.exe /f /s /q
del StarlightGUI.exp /f /s /q
del StarlightGUI.lib /f /s /q
del StarlightGUI.pdb /f /s /q
echo Done.
pause